ambitions_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :show] 
  resources :goals do
    resources :cheers, only: [:create]
  end

  resources :cheers, only: [:index]
  resources :comments, only: [:create]
end

ambitions_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ambitions_app/app/models/cheer.rb
# == Schema Information
#
# Table name: cheers
#
#  id         :bigint           not null, primary key
#  giver_id   :integer          not null
#  goal_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Cheer < ApplicationRecord
  validates :giver_id, :goal_id, presence: true
  validates :goal_id, uniqueness: { scope: :giver_id }

  belongs_to :giver,
  class_name: 'User',
  foreign_key: giver_id

  belongs_to :goal,
  class_name: 'Goal',
  foreign_key: goal_id




end

ambitions_app/app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :bigint           not null, primary key
#  title      :string           not null
#  details    :text             not null
#  private    :boolean          not null
#  completed  :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
class Goal < ApplicationRecord
  validates :title, :details, presence: true

  belongs_to :user,
  class_name: :User,
  foreign_key: :user_id

  has_many :cheers,
  class_name: 'Cheer',
  foreign_key: goal_id
end

ambitions_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#
class User < ApplicationRecord
  validates :username, :session_token, presence: true, uniqueness: true 
  validates :password_digest, presence: true 
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token

  has_many :goals,
  class_name: :Goal,
  foreign_key: :user_id

   has_many :cheers,
  class_name: 'Cheer',
  foreign_key: giver_id

  attr_reader :password 

  def self.find_by_credentials(username, password)
    @user = User.find_by(username: username)
    return user if @user && user.is_password?(password)
    nil
  end

  def is_password?
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

end

ambitions_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def require_current_user
    redirect_to new_user_url unless current_user
  end

  def require_no_current_user
    redirect_to root_url if current_user
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def require_logged_out
    redirect_to users_url if logged_in?
  end

  def log_in_user(user)
    session[:session_token] = user.reset_session_token
  end

  def logged_in?
    !!current_user
  end

  def log_out_user
    current_user.reset_session_token
    session[:session_token] = nil
    @current_user = nil 
  end

end

ambitions_app/app/controllers/cheers_controller.rb
class CheersController < ApplicationController

  def create

  end

  def index

  end

end

ambitions_app/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_current_user

  def new 
    @goal = Goal.new 
    render :new 
  end


  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id 
    if @goal.save 
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new 
    end
  end

  def index 
    @goals = current_user.goals
    render :index
  end

  def show 
    @goal = Goal.find(params[:id])
    render :show
  end

  def edit
    @goal = Goal.find(params[:id])
    render :edit
  end

  def update 
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
       redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit 
    end
  end

  def destroy 
    @goal = Goal.find(params[:id])
    if @goal && @goal.destroy
      redirect_to goals_url
    end
  end

private 

  def goal_params
    params.require(:goal).permit(:title, :details, :private, :completed)
  end

end

ambitions_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #   resource :session, only: [:new, :create, :destroy]
 

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user
      log_in_user(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    end

  end

  def destroy
    log_out_user
    redirect_to new_session_url
  end

end

ambitions_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
 # resources :users, only: [:new, :create, :show]
  before_action :require_logged_in, only: [:show]
  before_action :require_logged_out, only: [:new, :create]

 def new
  @user = User.new
  render :new
 end

 def create
  @user = User.new(user_params)
  if @user.save
    log_in_user(@user)
    redirect_to user_url(@user)
  else
    flash.now[:errors] = @user.errors.full_messages
    render :new
  end
 end

 def index
  @users = User.all 
  render :index
 end

 def show
  @user = User.find_by(id: params[:id])
  render :show
 end

 private 

 def user_params
  params.require(:user).permit(:username, :password)
 end
  
end

ambitions_app/app/helpers/application_helper.rb
module ApplicationHelper
end

ambitions_app/app/helpers/cheers_helper.rb
module CheersHelper
end

ambitions_app/app/helpers/goals_helper.rb
module GoalsHelper
end

ambitions_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

ambitions_app/app/helpers/users_helper.rb
module UsersHelper
end

ambitions_app/app/views/goals/edit.html.erb
<h1>Edit <%= @goal.title %></h1>

<form action="<%= goal_url(@goal) %>" method="post">
<input type="hidden" name="_method" value="patch">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<label for="title">Title:</label>
<input type="text" name="goal[title]" id="title" value="<%= @goal.title %>">


<label for="details">Details:</label>
<textarea name="goal[details]" id="details">
<%= @goal.details %>
</textarea>

<label for="private_true">Private</label>
<input type="radio" name="goal[private]" id="private_true" value="true"   
<%= "checked" if @goal.private %>
>

<label for="private_false">Public</label>
<input type="radio" name="goal[private]" id="private_false" value="false"
<%= "checked" if !@goal.private %>>

<label for="completed">Completed?</label>
<input type="checkbox" name="goal[completed]" id="completed" value="true"
<%= "checked" if @goal.completed %>>

<input type="submit" value="Submit Edit of Goal!">
</form>

ambitions_app/app/views/goals/index.html.erb
<h1>All my goals</h1>
<ul>
<% @goals.each do |goal| %>
<li><a href="<%= goal_url(goal) %>"><%= goal.title %></a><form action="<%= goal_url(goal) %>" method="post">
<input type="hidden" name="_method" value="delete">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<input type="submit" value="delete">
</form></li>

<% end %>
</ul>
<% if @goals.count == 0 %>
Feeling unmotivated? You have ZERO goals :( <p>
  <% end %>
<a href="<%= new_goal_url %>">Create a goal</a>

ambitions_app/app/views/goals/new.html.erb
<h1>Create A GOAL</h1>

<form action="<%= goals_url %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<label for="title">Title:</label>
<input type="text" name="goal[title]" id="title" value="<%= @goal.title %>">


<label for="details">Details:</label>
<textarea name="goal[details]" id="details">
<%= @goal.details %>
</textarea>

<label for="private_true">Private</label>
<input type="radio" name="goal[private]" id="private_true" value="true">

<label for="private_false">Public</label>
<input type="radio" name="goal[private]" id="private_false" value="false">

<label for="completed">Completed?</label>
<input type="checkbox" name="goal[completed]" id="completed" value="true">

<input type="submit" value="Create Goal!">
</form>

ambitions_app/app/views/goals/show.html.erb
<h1>This is your <%= @goal.title %>'s showpage</h1>

<ul>
  
  <li><%= @goal.title %></li>
  <li><%= @goal.details %></li>
  <li>Finished? <%= @goal.completed %></li>
    <% if @goal.private %>
  <li>This goal is private</li>
    <% else %>
    <li>This goal is public </li>
  <% end %>
</ul>
<a href="<%= edit_goal_url(@goal) %>">Edit this goal</a><br /><p>
<form action="<%= goal_url(@goal) %>" method="post">
<input type="hidden" name="_method" value="delete">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<input type="submit" value="delete this goal">
</form>
<hr>
<a href="<%= goals_url %>">See all goals</a><br />
<a href="<%= user_url(current_user) %>">See my profile</a><br />

ambitions_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AmbitionsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <% if logged_in? %>
    <%# #option to logout
    #welcome message %>
    <form action="<%= session_url %>" method="post">
      <input type="hidden" name="_method" value="delete">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">
    <input type="submit" value="Log Out">
    </form>

  <% else %>
    <a href="<%= new_user_url %>">Sign up!</a>
    <a href="<%= new_session_url %>">Log in!</a>
  <% end %>

  <body>
    <%= yield %>
  </body>
    <% if flash[:errors] %>
      <ul>
        <% flash[:errors].each do |error| %>
        <li><%= error %></li>
      </ul>

    <% end %>
    <% end %>

</html>

ambitions_app/app/views/users/index.html.erb
<h1>All the Users!</h1>
<ul>
<% @users.each do |user| %>
<li><a href="<%= user_url(user) %>"><%= user.username %></a></li>
<% end %>
</ul>

ambitions_app/app/views/users/new.html.erb
<h1>Create a user page</h1>
<form action="<%= users_url %>" method="post">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
<label>Username: 
<input type="text" name="user[username]" value="<%= @user.username %>">
</label>
<label>Password: 
<input type="password" name="user[password]" value="">
</label>
<input type="submit" value="Create user!">





</form>

ambitions_app/app/views/users/show.html.erb
<h1><%= @user.username %>'s Profile Page</h1>

<%# comment form %>
<% if @user.goals.count > 0 %>
<%= @user.username %>'s <%= @user.goals.count %> Goals:
<%#  show each goal %>
<% else %>
No Goals Yet :(
<% end %>

<%# new goal link %>

<a href="<%= new_goal_url %>">Create a new goal!</a>
<%# my cheers link %>
<%# all users %>

<a href="<%= users_url %>">All users</a>